change repository from goharbor to test

diff --git a/.github/workflows/harbor-multi-arch-images.yaml b/.github/workflows/harbor-multi-arch-images.yaml
--- a/.github/workflows/harbor-multi-arch-images.yaml
+++ b/.github/workflows/harbor-multi-arch-images.yaml
@@ -9,168 +9,166 @@ on:
     branches:
       - "master"
 jobs:
-  docker-base-image:
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-    strategy:
-      fail-fast: false
-      matrix:
-        component:
-          - trivy-adapter
-          - core
-          - db
-          - exporter
-          - jobservice
-          - log
-          - nginx
-          - portal
-          - prepare
-          - redis
-          - registry
-          - registryctl
+  # docker-base-image:
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       component:
+  #         - trivy-adapter
+  #         - core
+  #         - db
+  #         - exporter
+  #         - jobservice
+  #         - log
+  #         - nginx
+  #         - portal
+  #         - prepare
+  #         - redis
+  #         - registry
+  #         - registryctl
 
-    defaults:
-      run:
-        working-directory: ./
+  #   defaults:
+  #     run:
+  #       working-directory: ./
 
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
 
-      - uses: docker/setup-qemu-action@v2
-      - uses: docker/setup-buildx-action@v2
-        with:
-          driver: docker-container
-          driver-opts: network=host
-      - uses: docker/login-action@v2
-        with:
-          registry: minregi.k3.acornsoft.io
-          username: admin
-          password: Pass0000@
+  #     - uses: docker/setup-qemu-action@v2
+  #     - uses: docker/setup-buildx-action@v2
+  #       with:
+  #         driver: docker-container
+  #         driver-opts: network=host
+  #     - uses: docker/login-action@v2
+  #       with:
+  #         registry: minregi.k3.acornsoft.io
+  #         username: admin
+  #         password: Pass0000@
 
-      - run: make patch
+  #     - run: make patch
 
-      - id: prepare
-        run: echo "tag=$(cat ./version)"  >> $GITHUB_ENV
+  #     - id: prepare
+  #       run: echo "tag=$(cat ./version)"  >> $GITHUB_ENV
 
-      - name: Check if component is db
-        if: ${{ (matrix.component == 'db') }}
-        run: |
-          bash ./scripts/convert.sh ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
-          cat ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
+  #     - name: Check if component is db
+  #       if: ${{ (matrix.component == 'db') }}
+  #       run: |
+  #         bash ./scripts/convert.sh ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
+  #         cat ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
 
-      - name: Build base image
-        uses: docker/build-push-action@v4
-        with:
-          context: ./harbor
-          file: ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
-          platforms: linux/amd64,linux/arm64
-          # labels: |
-          #   org.opencontainers.image.source=https://github.com/${{ github.repository }}
-          #   org.opencontainers.image.revision=${{ env.tag }}
-          push: ${{ github.event_name != 'pull_request' }}
-          tags: minregi.k3.acornsoft.io/goharbor/harbor-${{ matrix.component }}-base:${{ env.tag }}
+  #     - name: Build base image
+  #       uses: docker/build-push-action@v4
+  #       with:
+  #         context: ./harbor
+  #         file: ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
+  #         platforms: linux/amd64,linux/arm64
+  #         # labels: |
+  #         #   org.opencontainers.image.source=https://github.com/${{ github.repository }}
+  #         #   org.opencontainers.image.revision=${{ env.tag }}
+  #         push: ${{ github.event_name != 'pull_request' }}
+  #         tags: minregi.k3.acornsoft.io/goharbor/harbor-${{ matrix.component }}-base:${{ env.tag }}
 
-  docker-image:
-    needs:
-      - docker-base-image
+  # docker-image:
+  #   needs:
+  #     - docker-base-image
 
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-    strategy:
-      fail-fast: false
-      matrix:
-        component:
-          - prepare
-          - db
-          - portal
-          - core
-          - jobservice
-          - log
-          - nginx
-          - registryctl
-          - trivy_adapter
-          - redis
-          - standalone_db_migrator
-          - exporter
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       component:
+  #         - prepare
+  #         - db
+  #         - portal
+  #         - core
+  #         - jobservice
+  #         - log
+  #         - nginx
+  #         - registryctl
+  #         - trivy_adapter
+  #         - redis
+  #         - standalone_db_migrator
+  #         - exporter
 
-    defaults:
-      run:
-        working-directory: ./
+  #   defaults:
+  #     run:
+  #       working-directory: ./
 
-    steps:
-      - id: prepare
-        run: echo "tag=$(cat ./version)"  >> $GITHUB_ENV
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
+  #   steps:
+  #     - id: prepare
+  #       run: echo "tag=$(cat ./version)"  >> $GITHUB_ENV
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
 
-      - uses: actions/setup-go@v3
-        with:
-          go-version: "^1.20.x"
+  #     - uses: actions/setup-go@v3
+  #       with:
+  #         go-version: "^1.20.x"
 
-      - uses: docker/setup-qemu-action@v2
-      - uses: docker/setup-buildx-action@v2
-        with:
-          driver: docker-container
-          driver-opts: network=host
+  #     - uses: docker/setup-qemu-action@v2
+  #     - uses: docker/setup-buildx-action@v2
+  #       with:
+  #         driver: docker-container
+  #         driver-opts: network=host
 
-      - run: make patch
+  #     - run: make patch
 
-      - uses: docker/login-action@v2
-        with:
-          registry: minregi.k3.acornsoft.io
-          username: admin
-          password: Pass0000@
+  #     - uses: docker/login-action@v2
+  #       with:
+  #         registry: minregi.k3.acornsoft.io
+  #         username: admin
+  #         password: Pass0000@
 
-      - id: versioning
-        run: echo "tag=$(cat ./version)" >> $GITHUB_ENV
+  #     - id: versioning
+  #       run: echo "tag=$(cat ./version)" >> $GITHUB_ENV
 
-      - name: Check if component is db
-        if: ${{ (matrix.component == 'db') }}
-        run: |
-          bash ./scripts/convert.sh ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
-          cat ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
+  #     - name: Check if component is db
+  #       if: ${{ (matrix.component == 'db') }}
+  #       run: |
+  #         bash ./scripts/convert.sh ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
+  #         cat ./harbor/make/photon/${{ matrix.component }}/Dockerfile.base
 
-      - name: Build & Publish images
-        env:
-          IMAGENAMESPACE: minregi.k3.acornsoft.io/goharbor
-          BASEIMAGENAMESPACE: minregi.k3.acornsoft.io/goharbor
-          IMAGELABELS: org.opencontainers.image.source=https://minregi.k3.acornsoft.io/goharbor
-          MULTIARCH: true
-          TRIVYFLAG: true
-          CHARTFLAG: true
-          NOTARYFLAG: true
-          PUSHBASEIMAGE: true
-        run: |
-          cd ./harbor;
-          set -eux;
+  #     - name: Build & Publish images
+  #       env:
+  #         IMAGENAMESPACE: minregi.k3.acornsoft.io/goharbor
+  #         BASEIMAGENAMESPACE: minregi.k3.acornsoft.io/goharbor
+  #         IMAGELABELS: org.opencontainers.image.source=https://minregi.k3.acornsoft.io/goharbor
+  #         MULTIARCH: true
+  #         TRIVYFLAG: true
+  #         CHARTFLAG: true
+  #         NOTARYFLAG: true
+  #         PUSHBASEIMAGE: true
+  #       run: |
+  #         cd ./harbor;
+  #         set -eux;
 
-          CTX="BUILDBIN=true VERSIONTAG=${{ env.tag }} BASEIMAGETAG=${{ env.tag }}  MULTIARCH=${MULTIARCH} IMAGENAMESPACE=${IMAGENAMESPACE} BASEIMAGENAMESPACE=${BASEIMAGENAMESPACE} TRIVYFLAG=${TRIVYFLAG} CHARTFLAG=${CHARTFLAG} NOTARYFLAG=${CHARTFLAG} IMAGELABELS=${IMAGELABELS} PUSHBASEIMAGE=${PUSHBASEIMAGE}"
+  #         CTX="BUILDBIN=true VERSIONTAG=${{ env.tag }} BASEIMAGETAG=${{ env.tag }}  MULTIARCH=${MULTIARCH} IMAGENAMESPACE=${IMAGENAMESPACE} BASEIMAGENAMESPACE=${BASEIMAGENAMESPACE} TRIVYFLAG=${TRIVYFLAG} CHARTFLAG=${CHARTFLAG} NOTARYFLAG=${CHARTFLAG} IMAGELABELS=${IMAGELABELS} PUSHBASEIMAGE=${PUSHBASEIMAGE}"
 
-          make versions_prepare ${CTX};
+  #         make versions_prepare ${CTX};
 
-          case ${{ matrix.component }} in
-            core)                   make compile_core ${CTX} ;;
-            jobservice)             make compile_jobservice ${CTX};;
-            registryctl)            make compile_registryctl ${CTX};;
-            standalone_db_migrator) make compile_standalone_db_migrator ${CTX} ;;
-          esac;
+  #         case ${{ matrix.component }} in
+  #           core)                   make compile_core ${CTX} ;;
+  #           jobservice)             make compile_jobservice ${CTX};;
+  #           registryctl)            make compile_registryctl ${CTX};;
+  #           standalone_db_migrator) make compile_standalone_db_migrator ${CTX} ;;
+  #         esac;
 
-          case ${{ matrix.component }} in
-            exporter)    make build BUILDTARGET="_compile_and_build_exporter" ${CTX} ;;
-            registryctl) make build BUILDTARGET="_build_registry _build_registryctl" ${CTX} ;;
-            *)           make build BUILDTARGET="_build_${{ matrix.component }}" ${CTX} ;;
-          esac;
+  #         case ${{ matrix.component }} in
+  #           exporter)    make build BUILDTARGET="_compile_and_build_exporter" ${CTX} ;;
+  #           registryctl) make build BUILDTARGET="_build_registry _build_registryctl" ${CTX} ;;
+  #           *)           make build BUILDTARGET="_build_${{ matrix.component }}" ${CTX} ;;
+  #         esac;
 
   docker-package:
-    needs: docker-image
-
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -209,33 +207,33 @@ jobs:
 
       - name: Load remote Docker image
         run: |
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-trivy-adapter-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-core-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-db-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-exporter-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-jobservice-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-log-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-nginx-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-portal-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-prepare-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-redis-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-registry-base:${{ env.tag }}
-          docker pull minregi.k3.acornsoft.io/goharbor/harbor-registryctl-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-trivy-adapter-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-core-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-db-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-exporter-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-jobservice-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-log-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-nginx-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-portal-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-prepare-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-redis-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-registry-base:${{ env.tag }}
+          docker pull minregi.k3.acornsoft.io/test/harbor-registryctl-base:${{ env.tag }}
 
       - name: Changing the tag of the base image
         run: |
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-trivy-adapter-base:${{ env.tag }} goharbor/trivy-adapter-photon:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-core-base:${{ env.tag }} goharbor/harbor-core:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-db-base:${{ env.tag }} goharbor/harbor-db:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-exporter-base:${{ env.tag }} goharbor/harbor-exporter:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-jobservice-base:${{ env.tag }} goharbor/harbor-jobservice:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-log-base:${{ env.tag }} goharbor/harbor-log:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-nginx-base:${{ env.tag }} goharbor/nginx-photon:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-portal-base:${{ env.tag }} goharbor/harbor-portal:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-prepare-base:${{ env.tag }} goharbor/prepare:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-redis-base:${{ env.tag }} goharbor/redis-photon:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-registry-base:${{ env.tag }} goharbor/registry-photon:${{ env.tag }}
-          docker tag minregi.k3.acornsoft.io/goharbor/harbor-registryctl-base:${{ env.tag }} goharbor/harbor-registryctl:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-trivy-adapter-base:${{ env.tag }} goharbor/trivy-adapter-photon:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-core-base:${{ env.tag }} goharbor/harbor-core:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-db-base:${{ env.tag }} goharbor/harbor-db:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-exporter-base:${{ env.tag }} goharbor/harbor-exporter:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-jobservice-base:${{ env.tag }} goharbor/harbor-jobservice:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-log-base:${{ env.tag }} goharbor/harbor-log:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-nginx-base:${{ env.tag }} goharbor/nginx-photon:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-portal-base:${{ env.tag }} goharbor/harbor-portal:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-prepare-base:${{ env.tag }} goharbor/prepare:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-redis-base:${{ env.tag }} goharbor/redis-photon:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-registry-base:${{ env.tag }} goharbor/registry-photon:${{ env.tag }}
+          docker tag minregi.k3.acornsoft.io/test/harbor-registryctl-base:${{ env.tag }} goharbor/harbor-registryctl:${{ env.tag }}
 
       - name: Docker packaging Offline installer
 
